[package]
name = "filefs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
bitvec = { version = "1.0.1", features = ["serde"]}
byteorder = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
